<Project>
  <PropertyGroup>
    <UsePrivateTests Condition="'$(UsePrivateTests)' == ''">false</UsePrivateTests>
    <PrivateTestPackageId Condition="'$(PrivateTestPackageId)' == ''">WongCyrus.AzureProjectTestLib.Private</PrivateTestPackageId>
    <PrivateTestPackageVersion Condition="'$(PrivateTestPackageVersion)' == ''">1.0.4</PrivateTestPackageVersion>
  </PropertyGroup>
</Project>
