#!/bin/bash
# This script writes Azure AD B2C environment variables from Terraform outputs into the .env file for local development

set -e

# Navigate to the Infrastructure directory
cd "$(dirname "$0")"


# Use outputs.json generated by cdktf output
TF_OUTPUTS_FILE="outputs.json"

# Ensure outputs.json is up to date
cdktf output AzureAutomaticGradingEngineGrader --outputs-file outputs.json --outputs-file-include-sensitive-outputs

if [[ ! -f "$TF_OUTPUTS_FILE" ]]; then
  echo "Error: $TF_OUTPUTS_FILE not found after output."
  exit 1
fi

# Extract values using jq from outputs.json
CLIENT_ID=$(jq -r '.AzureAutomaticGradingEngineGrader.AADB2C_PROVIDER_CLIENT_ID // empty' "$TF_OUTPUTS_FILE")
CLIENT_SECRET=$(jq -r '.AzureAutomaticGradingEngineGrader.AADB2C_PROVIDER_CLIENT_SECRET // empty' "$TF_OUTPUTS_FILE")
AUTHORITY=$(jq -r '.AzureAutomaticGradingEngineGrader.AADB2C_PROVIDER_AUTHORITY // empty' "$TF_OUTPUTS_FILE")


# Check if values are present
if [[ -z "$CLIENT_ID" || -z "$CLIENT_SECRET" || -z "$AUTHORITY" ]]; then
  echo "Error: Missing one or more required outputs (CLIENT_ID, CLIENT_SECRET, AUTHORITY) in $TF_OUTPUTS_FILE."
  exit 1
fi

# Write to .env in azure-isekai folder
ENV_FILE="../azure-isekai/.env"
echo "AADB2C_PROVIDER_CLIENT_ID=$CLIENT_ID" > "$ENV_FILE"
echo "AADB2C_PROVIDER_CLIENT_SECRET=$CLIENT_SECRET" >> "$ENV_FILE"
echo "AADB2C_PROVIDER_AUTHORITY=$AUTHORITY" >> "$ENV_FILE"

echo ".env file updated at $ENV_FILE"
